admin:
  enabled: true
  http:
    enabled: true
    port: 8001
    containerPort: 8001
  tls:
    enabled: true
    port: 8444
    containerPort: 8444
manager:
  enabled: true
  http:
    enabled: true
    port: 8002
    containerPort: 8002
  tls:
    enabled: true
    port: 8445
    containerPort: 8445
gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.10"
  service:
    http:
      enabled: true
      port: 80
      targetPort: 8000
    https:
      enabled: true
      port: 443
      targetPort: 8443
  env:
    vitals: "off"
    lua_ssl_trusted_certificate: system
    nginx_worker_processes: "1"
    upstream_keepalive_max_requests: "100000"
    nginx_http_keepalive_requests: "100000"
    proxy_access_log: "off"
    dns_stale_ttl: "3600"
    KONG_DATABASE: "off"
    KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    KONG_PROXY_ACCESS_LOG: /dev/stdout
    KONG_ADMIN_ACCESS_LOG: /dev/stdout
    KONG_PROXY_ERROR_LOG: /dev/stderr
    KONG_ADMIN_ERROR_LOG: /dev/stderr
  extraVolumes:
    - name: kong-declarative-config-volume
      configMap:
        name: kong-declarative-config
  extraVolumeMounts:
    - name: kong-declarative-config-volume
      mountPath: /opt/kong/kong.yaml
      subPath: kong.yaml
