image:
  repository: kong/kong-gateway
  tag: "3.10"
env:
  vitals: "off"
  lua_ssl_trusted_certificate: system
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  database: "off"
  log_level: debug
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdou
  proxy_error_log: /dev/stderr
  admin_error_log: /dev/stderr
admin:
  enabled: true
  http:
    enabled: true
    port: 8001
    containerPort: 8001
  tls:
    enabled: true
    port: 8444
    containerPort: 8444
manager:
  enabled: true
  http:
    enabled: true
    port: 8002
    containerPort: 8002
  tls:
    enabled: true
    port: 8445
    containerPort: 8445
